# Generated by Django 4.2.28 on 2026-02-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bot Log',
                'verbose_name_plural': 'Bot Logs',
            },
        ),
        migrations.CreateModel(
            name='Fermos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(blank=True, max_length=255)),
                ('player_name', models.CharField(blank=True, max_length=255)),
                ('tribe', models.CharField(blank=True, max_length=30)),
                ('alliance', models.CharField(blank=True, max_length=255)),
                ('population', models.CharField(blank=True, max_length=20)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('lumber', models.IntegerField(blank=True, default=0)),
                ('clay', models.IntegerField(blank=True, default=0)),
                ('iron', models.IntegerField(blank=True, default=0)),
                ('crop', models.IntegerField(blank=True, default=0)),
                ('resource_cap', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Grupes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupes',
                'verbose_name_plural': 'Grupes',
            },
        ),
        migrations.CreateModel(
            name='Nustatymai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nustatymai',
                'verbose_name_plural': 'Nustatymai',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
