# Generated by Django 4.2.28 on 2026-02-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grupes',
        ),
        migrations.DeleteModel(
            name='Nustatymai',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='fermos',
            name='battering_ram',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='equites_caesaris',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='equites_imperatoris',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='equites_legati',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='fire_catapult',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='hero',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='imperian',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='legionnaire',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='lost_battering_ram',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='lost_equites_caesaris',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='lost_equites_imperatoris',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='lost_equites_legati',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='lost_fire_catapult',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='lost_hero',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='lost_imperian',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='lost_legionnaire',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='lost_praetorian',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='lost_senator',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='lost_settler',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='praetorian',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='senator',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fermos',
            name='settler',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
