# Generated by Django 4.2.28 on 2026-02-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_delete_grupes_delete_nustatymai_delete_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermos',
            name='farm_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fermos',
            name='farm_status_comment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
