# Generated by Django 4.2.28 on 2026-02-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_fermos_farm_status_fermos_farm_status_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermos',
            name='warehouse_capacity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
